title: Leah Bannon
tagline: "product manager and civic hacker"

#Jekyll config file

#title of site
name: Leah Bannon

#description of site
description: "Hi. Iâ€™m an open gov consultant and digital strategist."

#URL of site, include http://, do not include a trailing slash
url: "http://leah.io"

#description of site
description: "GitHubber, Gov 2.0 Evangelist, Aspiring Attorney"

  #permalink structure, see https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/

#files to exclude, array
exclude:
  - CONTRIBUTING.md
  - README.md
  - LICENSE
  - readme.md
  - bundle
  - src
  - CNAME
  - Gemfile
  - Gemfile.lock
  - bower.json
  - package.json
  - script
  - test
  - less
  - scss
  - media
  - feature-detects
  - composer.json
  - component.json
  - grunt.js

#google analytics username
ga_username: 'UA-47016218-1'

##local dev stuff
server: true
auto: true

#build config
highlighter: true
markdown: kramdown
timezone: America/New_York
encoding: UTF-8

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
